language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "node"
  - "iojs"
install:
  npm install -g codecov
  npm install -g istanbul
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8