language: node_js
node_js:
- '7'
- '6'
- node
install:
- npm install
script:
- npm test
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: PmiPta2PsLKwMKi35LEle0f9n95hODkuBCFHzKbJ9r2Tn/1q31g/o3dJQ/5a2D+N0GhSrj+QA2lmeXp7UyMzNACWNsEhiqz+0rGMuBF0qzdfJN4ilYDg+HqZbUlplY/BISrdpI3VW995Lii3THlYFSxNMIzFV83LUdE4oPi9ETLHVLTRJcbkabq2Bn0NQ+Y0WAi8FVUluHUgRoDljpsivW/vRN9vnf0559ZuZRBBx4dwEcyW5/7/yug5fqdu476xyE53W27X1YBwrdHEy6IIC6aeagda0g5C2J7WrUzO6a2E3gIFYLr9CQkKzov8mKrg2xXAHxgXs51owreV1HstGtxUPcwFNZDGgSyPgawZojSKWYBwr4Mewu8UOQyrzZDZJa7sILBznMuHS8756N5rq7PXwU76H4UQv9aGPfV7dXIeL2UhCQdMllovVU2cd+YT/Fz/2FRTZsYF8h91Iowuyp8pMpqeeaFQ76YDLH4hYlYRPjKdK6XUPvidEpeOO5LDHzm2pNBNf/WEWZioH1gqP9viOBlhrEXuuh4Ugxj2we5BlwjLEcy/J/kqmW2uLrbcbNs8tLhG/0qhlAuHeWz+aHpJshwdMSural3fqkeZDMbEkeFTYwhRmLm6Pz09cSShdY+AUs1cG8qoxQ84SjbGk9ibTJnEYvrWc/6ZsJxABEY=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: npm
  email: headgeek@iamdigital.uk
  api_key:
    secure: vK5MTs2zl8Z0mexVQ/gdn8Pm9cNLfQqV1b4rpDoo/R6vrz1FB7FW3gHDChqafFjbdky6SkmSSvKPAns1kiFys+O4g2WAgswGvUkGHcpccks1eBjp4IGBBKfvh4xKsuexZzltVFzkYQyYmAbSQofPHvorjs6vQ3aK4xbqQt6uFrqg0QWZfU1LhSMxD9WQfrdA3H1KQKI0XvhpbnEGwQxnmRnxB732IAEeBwUhdj6J6cjvuotV329Ou432EzPJ7rcj/c39cQ8IZ87tDq1cXbqs/QB7XXVG1HZ+SemywXGAnGVVUsDTAgu0vU6H/Q8QPStxyxQ8iBvsFrc0wa7sAjeDJZ+dzpnRrgH8arV21F3uQ1KJAVB7JQD5U3GIRwq+s48iO8EUlgY/mBb96iwLYsz3/aK4XH9G1guPPRW8G3gCobK27Kn9BaGn526TwCSXWr+N3YnGEY9gtecBmXZuR7ow5VJJO1QHvvqzrvpO6IkEpnMVZvf5DAtFgeOToAIpKwdBTDsTCl6qg98VVI6fL3wZ2BzLAWNJP9nD7kpWjMid81D1ifoAdmv9u+IcHzkFGGOHaX4eTFmPjuPOR/YTq6zj7qnzRR8SerA7Hya6JQq65P1av4GcP1p5cAJ3/0wUBB5mOs+v1MQOSR4WqWb79APx75qNkdmQkECJvQ6m8NiHniA=
  on:
    tags: true
    repo: i-am-digital/js-gpiozero
