language: node_js
cache:
  directories:
  - node_modules
node_js:
  - '7'
  - '6'
install:
  - npm install
script:
  - npm test
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: PmiPta2PsLKwMKi35LEle0f9n95hODkuBCFHzKbJ9r2Tn/1q31g/o3dJQ/5a2D+N0GhSrj+QA2lmeXp7UyMzNACWNsEhiqz+0rGMuBF0qzdfJN4ilYDg+HqZbUlplY/BISrdpI3VW995Lii3THlYFSxNMIzFV83LUdE4oPi9ETLHVLTRJcbkabq2Bn0NQ+Y0WAi8FVUluHUgRoDljpsivW/vRN9vnf0559ZuZRBBx4dwEcyW5/7/yug5fqdu476xyE53W27X1YBwrdHEy6IIC6aeagda0g5C2J7WrUzO6a2E3gIFYLr9CQkKzov8mKrg2xXAHxgXs51owreV1HstGtxUPcwFNZDGgSyPgawZojSKWYBwr4Mewu8UOQyrzZDZJa7sILBznMuHS8756N5rq7PXwU76H4UQv9aGPfV7dXIeL2UhCQdMllovVU2cd+YT/Fz/2FRTZsYF8h91Iowuyp8pMpqeeaFQ76YDLH4hYlYRPjKdK6XUPvidEpeOO5LDHzm2pNBNf/WEWZioH1gqP9viOBlhrEXuuh4Ugxj2we5BlwjLEcy/J/kqmW2uLrbcbNs8tLhG/0qhlAuHeWz+aHpJshwdMSural3fqkeZDMbEkeFTYwhRmLm6Pz09cSShdY+AUs1cG8qoxQ84SjbGk9ibTJnEYvrWc/6ZsJxABEY=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
